### ISSUE TITLE
Pull tags from EC2 Instance

### ISSUE THREAD

**Issue by MikeKroell** [awslabs/amazon-ebs-autoscale#19]
When a volume is created with the instance, it pulls the tags from the instance. I've noticed that as of version 2.4.2, the only tags on the volume are that of the source instance and the time it was created. It would be nice if it pulled the instance tags as well, as when trying to track cost, there are no relevant tags to correlate off of. This makes it impossible to pull a fully accurate report on the cost of a Batch compute environment, as only EC2 costs and original volumes will be included, and not the volumes created from the autoscaler.

**Comment by wleepang** [comment]
This should have been addressed in PR #15 . Is this still not the case?

**Comment by MikeKroell** [comment]
@wleepang This does not appear to be the case for us. This is what we see:

Instance:
![image](https://user-images.githubusercontent.com/48728771/113354653-7c0cbe80-930d-11eb-9c30-472ac3451722.png)

Volume:
![image](https://user-images.githubusercontent.com/48728771/113354577-66979480-930d-11eb-9982-a67870e39594.png)

Instance IAM:
`BatchInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${BatchEnvironmentPrefix}-Batch-${Revision}-Instance-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: EBS-Autoscaler
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Action:
                - "ec2:AttachVolume"
                - "ec2:DescribeVolumeStatus"
                - "ec2:DescribeVolumes"
                - "ec2:ModifyInstanceAttribute"
                - "ec2:DescribeVolumeAttribute"
                - "ec2:CreateVolume"
                - "ec2:DeleteVolume"
                - "ec2:CreateTags"
              Resource: "*"
        - PolicyName: Cloudwatch
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
                - "logs:DescribeLogStreams"
              Resource: "*"
        - PolicyName: S3-Access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                    - arn:aws:s3:::go-shared-tools
                    - arn:aws:s3:::go-shared-tools/*
                Action:
                  - "s3:List*"
                  - "s3:Get*"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"`

**Comment by MikeKroell** [comment]
I had an old version, though I grabbed it in November. Anyways, my test shows it works fine.
