### ISSUE TITLE
/dev/sdb is not found, and scratchPath is undefined.

### ISSUE THREAD

**Issue by golharam** [awslabs/amazon-ebs-autoscale#4]
Depending on the version of linux used,  the install.sh will fail because linux changes /dev/sdb to /dev/xvdb instead.   This parameter to install.sh should probably be parameterized somewhere.

**Comment by golharam** [comment]
I also see $scratchPath in cloud-init-userdata.yaml, but its not read in from anywhere.

**Comment by golharam** [comment]
PR #3 fixes:
1) unzip is not installed
2) scratchPath is not defined

**Comment by wleepang** [comment]
I just pushed a bunch of updates that also happens to resolve the scratchPath part of this issue. Can you rebase your PR?

**Comment by wleepang** [comment]
Resolved in PR #5
