### ISSUE TITLE
/usr/local/bin/create-ebs-volume: line 264: else:: command not found

### ISSUE THREAD

**Issue by kcajf** [awslabs/amazon-ebs-autoscale#45]
https://github.com/awslabs/amazon-ebs-autoscale/blob/4ada279d5b49dfa97738b67756d4fe1a9a6ff771/bin/create-ebs-volume#L264

```
/usr/local/bin/create-ebs-volume: line 264: else:: command not found
```

Looks like this was broken in a recent commit by @gwright99 ?

**Comment by gwright99** [comment]
Yes, sorry about that @kcajf - I submitted a PR as soon as I realized a colon snuck in, but @wleepang fixed it first.
