### ISSUE TITLE
Improved error messaging

### ISSUE THREAD

**Issue by golharam** [awslabs/amazon-ebs-autoscale#6]
I'm running into an issue where volumes cannot be created:

[Tue Apr 28 04:24:23 UTC 2020] LOW DISK (50%): Adding more.
[Tue Apr 28 04:24:24 UTC 2020] Extending logical volume /scratch by 150GB
[Tue Apr 28 04:24:26 UTC 2020] next available device: /dev/xvdba
[Tue Apr 28 04:24:27 UTC 2020] created volume:
[Tue Apr 28 04:35:15 UTC 2020] Error creating or attaching EBS volume

This is odd because the instance IAMROLE has the necessary permissions.   I don't see an error anywhere.  Would be nice to include some error logging indicating what happened.

**Comment by golharam** [comment]
Looks like the instance isn't allowed to:
An error occurred (UnauthorizedOperation) when calling the CreateVolume operation: You are not authorized to perform this operation. Encoded authorization failure message: ...

when called 'aws ec2 create-volume'

Looks like the reason is because ec2:CreateTags is not permitted.   I'm following the IAM permissions listed in the README.md, so that should get updated.

**Comment by golharam** [comment]
This is addressed in PR #7

**Comment by wleepang** [comment]
Good catch. Also updated `create-ebs-volume` to capture any errors emitted by the `CreateVolume` call to logs.
