### ISSUE TITLE
Amazon Linux 2022 and btrfs

### ISSUE THREAD

**Issue by gilfreund** [awslabs/amazon-ebs-autoscale#60]
I was testing Amazon Linux 2022 and could not find btrfs. Look at the docs, it looks like it was [removed](https://docs.aws.amazon.com/linux/al2022/release-notes/removed-packages-al2022.html). I could not find any notes on why. 
Does anyone know more about this?

**Comment by wleepang** [comment]
Using `al2022-ami-ecs-hvm-2022.0.20220630-x86_64-ebs` in `us-east-1`, I see it available to install:

```
sudo dnf search btrfs
Last metadata expiration check: 0:01:25 ago on Tue 03 Jan 2023 11:12:14 PM UTC.
=========================================== Name & Summary Matched: btrfs ============================================
btrfs-progs.x86_64 : Userspace programs for btrfs
```

**Comment by gilfreund** [comment]
Following up [there](https://github.com/amazonlinux/amazon-linux-2022/discussions/251#discussion-4720709). 
For the moment I am using mdadm.

**Comment by gilfreund** [comment]
Just to note that btrst will not be implemented in AL 2022: https://github.com/amazonlinux/amazon-linux-2023/discussions/251
